"""Bake assets/structures/*.png into scripts/art/structure_sprites.gd as base64.

Also reports the non-transparent bounding box of each PNG so a clipped
render is caught here instead of in-game.
Run: python3 tools/bake_structure_sprites.py
"""
import base64
import os
import struct
import zlib

ROOT = os.path.expanduser("~/workspace/thugs-rts")
SRC = os.path.join(ROOT, "assets", "structures")
DST = os.path.join(ROOT, "scripts", "art", "structure_sprites.gd")
KEYS = ["hq_america", "hq_asia", "barracks_america", "barracks_asia"]


def png_rgba(path):
    """Minimal PNG decoder for 8-bit RGBA, no interlace."""
    data = open(path, "rb").read()
    assert data[:8] == b"\x89PNG\r\n\x1a\n", "not a PNG: " + path
    pos = 8
    w = h = None
    ctype = None
    raw = b""
    while pos < len(data):
        (ln,) = struct.unpack(">I", data[pos:pos + 4])
        typ = data[pos + 4:pos + 8]
        chunk = data[pos + 8:pos + 8 + ln]
        if typ == b"IHDR":
            w, h, depth, ctype, comp, filt, inter = struct.unpack(">IIBBBBB", chunk)
            assert depth == 8 and ctype == 6 and inter == 0, "need 8-bit RGBA non-interlaced"
        elif typ == b"IDAT":
            raw += chunk
        pos += 12 + ln
    px = zlib.decompress(raw)
    stride = w * 4
    out = bytearray(w * h * 4)
    prev = bytearray(stride)
    p = 0
    for y in range(h):
        f = px[p]
        p += 1
        line = bytearray(px[p:p + stride])
        p += stride
        if f == 1:
            for i in range(4, stride):
                line[i] = (line[i] + line[i - 4]) & 0xFF
        elif f == 2:
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 0xFF
        elif f == 3:
            for i in range(stride):
                a = line[i - 4] if i >= 4 else 0
                line[i] = (line[i] + ((a + prev[i]) >> 1)) & 0xFF
        elif f == 4:
            for i in range(stride):
                a = line[i - 4] if i >= 4 else 0
                b = prev[i]
                c = prev[i - 4] if i >= 4 else 0
                pp = a + b - c
                pa, pb, pc = abs(pp - a), abs(pp - b), abs(pp - c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pr) & 0xFF
        elif f != 0:
            raise ValueError("bad filter %d" % f)
        out[y * stride:(y + 1) * stride] = line
        prev = line
    return w, h, out


def alpha_bbox(w, h, px):
    minx, miny, maxx, maxy = w, h, -1, -1
    for y in range(h):
        for x in range(w):
            if px[(y * w + x) * 4 + 3] > 8:
                if x < minx:
                    minx = x
                if x > maxx:
                    maxx = x
                if y < miny:
                    miny = y
                if y > maxy:
                    maxy = y
    return minx, miny, maxx, maxy


def main():
    consts = []
    for key in KEYS:
        path = os.path.join(SRC, key + ".png")
        assert os.path.exists(path), "missing render: " + path
        w, h, px = png_rgba(path)
        bbox = alpha_bbox(w, h, px)
        print("%s: %dx%d alpha bbox %s" % (key, w, h, bbox), flush=True)
        assert bbox[2] >= 0, "empty render: " + key
        assert bbox[0] > 2 and bbox[2] < w - 3, "render touches left/right edge: " + key
        assert bbox[3] < h - 3, "render touches bottom edge: " + key
        b64 = base64.b64encode(open(path, "rb").read()).decode("ascii")
        consts.append('const _%s := "%s"' % (key.upper(), b64))
    body = "\n".join(consts)
    match_arms = "\n".join(
        '\t\t"%s":\n\t\t\tb64 = _%s' % (k, k.upper()) for k in KEYS
    )
    gd = '''# AUTO-GENERATED by tools/bake_structure_sprites.py - do not hand-edit.
class_name StructureSprites
extends RefCounted

## Blender-rendered structure sprites, embedded as base64 so the game
## never depends on the texture import pipeline (broken headless here).

%s


static var _tex_cache := {}


static func get_texture(key: String) -> Texture2D:
	if _tex_cache.has(key):
		return _tex_cache[key]
	var b64 := ""
	match key:
%s
		_:
			return null
	var img := Image.new()
	if img.load_png_from_buffer(Marshalls.base64_to_raw(b64)) != OK:
		return null
	var tex := ImageTexture.create_from_image(img)
	_tex_cache[key] = tex
	return tex
''' % (body, match_arms)
    with open(DST, "w") as f:
        f.write(gd)
    print("wrote %s (%d bytes)" % (DST, len(gd)), flush=True)


if __name__ == "__main__":
    main()
